"""Milestone 7.7 Case Comparison, Campaign Correlation & Cross-Investigation Analysis."""

from logintel.comparison.models import (
    CampaignCorrelationCandidate,
    CaseComparisonResult,
    ComparisonAISummaryRequest,
    ComparisonAISummaryResponse,
    ComparisonProvenanceManifest,
    ComparisonScopeDimension,
    CorrelationBasis,
    CorrelationReviewStatus,
    CorrelationType,
    CorroborationNature,
    CreateCaseComparisonRequest,
    CreateComparisonFindingRequest,
    EpistemicStatus,
    EvidenceGapComparison,
    ReviewCorrelationRequest,
    SharedEntity,
    SharedFindingPattern,
    SharedHuntPattern,
    TemporalComparisonWindow,
    TemporalOverlapResult,
)
from logintel.comparison.service import CaseComparisonService, case_comparison_service

__all__ = [
    "CampaignCorrelationCandidate",
    "CaseComparisonResult",
    "CaseComparisonService",
    "ComparisonAISummaryRequest",
    "ComparisonAISummaryResponse",
    "ComparisonProvenanceManifest",
    "ComparisonScopeDimension",
    "CorrelationBasis",
    "CorrelationReviewStatus",
    "CorrelationType",
    "CorroborationNature",
    "CreateCaseComparisonRequest",
    "CreateComparisonFindingRequest",
    "EpistemicStatus",
    "EvidenceGapComparison",
    "ReviewCorrelationRequest",
    "SharedEntity",
    "SharedFindingPattern",
    "SharedHuntPattern",
    "TemporalComparisonWindow",
    "TemporalOverlapResult",
    "case_comparison_service",
]
